# Generated by Django 5.1.6 on 2025-05-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='createdat',
            field=models.DateTimeField(default='2024-12-12'),
        ),
    ]
