# Generated by Django 5.1.1 on 2025-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_customer_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shipingadress',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
