# Generated by Django 5.1.1 on 2025-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_order_order_iterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
